---
groups:
- name: develop
  jobs:
  - prepare-itest-env
  - build-simple
  - itest-simple
  - itest-all
- name: publish
  jobs:
  - simple-major
  - simple-minor

##################################################
# RESOURCES
##################################################
resources:
- name: pipeline
  type: git
  source:
    uri: {{pipeline-git-uri}}
    branch: {{pipeline-git-branch}}
    #privage_key: {{git-private-key}}

#### PCF
- name: simple
  type: git
  source:
    uri: {{simple-git-uri}}
    branch: {{simple-git-branch}}
    #private_key: {{git-private-key}}

- name: simple-version
  type: semver
  source:
    driver: git
    uri: {{simple-git-version-uri}}
    branch: {{simple-git-version-branch}}
    file: number
    initial_version: 1.0.0-rc.0
    private_key: {{git-private-key}}

- name: simple-milestone
  type: s3
  source:
    bucket: {{s3-bucket-milestone}}
    regexp: simple-(.*).tar.gz
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    #endpoint: {{s3-endpoint}}
    region_name: us-west-2

- name: simple-release
  type: s3
  source:
    bucket: {{s3-bucket-release}}
    regexp: simple-(.*).tar.gz
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    #endpoint: {{s3-endpoint}}
    region_name: us-west-2

##################
#### PCF
##################
- name: cf-itest
  type: cf
  source:
    api: {{cf-api-url}}
    skip_cert_check: true
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}

- name: cf-prod
  type: cf
  source:
    api: {{cf-api-url}}
    skip_cert_check: true
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}

cf-params: &cf-params
  CF_API_URL: {{cf-api-url}}
  CF_SKIP_SSL: {{cf-skip-ssl}}
  CF_USERNAME: {{cf-username}}
  CF_PASSWORD: {{cf-password}}
  CF_ORG: {{cf-org}}
  CF_SPACE: {{cf-space}}

##################################################
# JOBS
##################################################
jobs:
- name: prepare-itest-env
  plan:
  - get: pipeline
  - task: prepare-cf
    file: pipeline/ci/prepare-cf.yml
    params:
      <<: *cf-params
      CF_DB_SERVICE_URL: {{cf-oracle-service-url}}
      CF_DB_SERVICE_USERNAME: {{cf-oracle-service-username}}
      CF_DB_SERVICE_PASSWORD: {{cf-oracle-service-password}}
      CF_REDIS_SERVICE: {{cf-redis-service}}
      CF_RABBIT_SERVICE: {{cf-rabbit-service}}

#### SIMPLE
- name: build-simple
  serial_groups: [ simple-version ]
  plan:
  - aggregate:
    - get: pipeline
    - get: project
      resource: simple
      trigger: true
    - get: version
      resource: simple-version
      params: { pre: rc }
  - task: build
    file: pipeline/ci/build.yml
    params:
      ARTIFACT_ID: simple
  - put: simple-milestone
    params: { file: build-output/simple-*.tar.gz }
  - put: simple-version
    params: { file: version/number }

- name: itest-simple
  serial: true
  plan:
  - aggregate:
    - get: pipeline
      passed: [ prepare-itest-env ]
    - get: release
      resource: simple-milestone
      passed: [ build-simple ]
      trigger: true
  - task: prepare-manifest
    file: pipeline/ci/prepare-manifest.yml
    params:
      <<: *cf-params
      CF_APP_NAME: {{cf-simple-name}}
      CF_APP_HOST: {{cf-simple-host}}
      CF_APP_SERVICES: {{cf-simple-services}}
      CF_ARTIFACT_ID: simple
  - put: cf-itest
    params:
      manifest: prepare-manifest-output/manifest.yml
      current_app_name: {{cf-simple-name}}

- name: simple-major
  serial_groups: [ simple-version ]
  plan:
  - get: simple-version
    params: { bump: major, pre: rc }
  - put: simple-version
    params: { file: simple-version/number }

- name: simple-minor
  serial_groups: [ simple-version ]
  plan:
  - get: simple-version
    params: { bump: minor, pre: rc }
  - put: simple-version
    params: { file: simple-version/number }

################
#### itest-all
################
- name: itest-all
  serial: true
  plan:
  - get: pipeline
    passed: [ itest-simple]
    trigger: true
  - task: itest-all
    file: pipeline/ci/itest-all.yml




